import type { Metadata } from "next";
import NavBar from "@/components/nav-bar";
import Logo from "@/components/logo";
import AuthBlock from "@/components/auth-block";
import Background from "@/components/main/background";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function HomeLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-lvh bg-black justify-center items-center flex flex-col">
      <header className="flex items-center justify-center top-0 bg-transparent h-24 sticky w-full backdrop-blur-sm z-99">
        <Logo color="text-white" />
        <NavBar />
        <AuthBlock />
      </header>

      <Background />
      {children}
    </div>
  );
}
